bankers_algorithm: bankers_algorithm.o
	gcc -o bankers_algorithm bankers_algorithm.o -lstdc++
bankers_algorithm.o: bankers_algorithm.cpp
	gcc -c bankers_algorithm.cpp -lstdc++
clean:
	rm bankers_algorithm bankers_algorithm.o