bankers_algorithm: bankers_algorithm.o
	gcc -o bankers_algorithm bankers_algorithm.o
bankers_algorithm.o: bankers_algorithm.cpp
	gcc -c bankers_algorithm.cpp
clean:
	rm bankers_algorithm bankers_algorithm.o
